<footer>
        <p>
            &copy; 2025 Hogwarts School of Witchcraft and Wizardry |
            <a href="https://cos10026tuesgroup3.atlassian.net/jira/software/projects/CJWDP/boards/34" target="_blank">Jira</a> |
            <a href="https://github.com/Swinburne105923830/COS10026-Web-Technology-Assessment.git" target="_blank">GitHub</a> |
            <a href="mailto:info@hogwarts.com">info@hogwarts.com</a>
        </p>
    </footer>