<header>
        <img src="images/Hogwarts-Crest.png" alt="Hogwarts Crest" class="logo">
        <div>
            <h1>Hogwarts School of Witchcraft and Wizardry</h1>
            <p class="slogan">Unlocking Magic, Inspiring Minds</p>
            <nav>
                <ul>
                    <li><a href="index.html" style="color:#aaa">Home</a></li>
                    <li><a href="jobs.html">Jobs</a></li>
                    <li><a href="apply.html">Apply</a></li>
                    <li><a href="about.html">About</a></li>
                </ul>

            </nav>
        </div>
    </header>