<header>
        <img src="images/Hogwarts-Crest.png" alt="Hogwarts Crest" class="logo">
        <div>
            <h1>Hogwarts School of Witchcraft and Wizardry</h1>
            <p class="slogan">Unlocking Magic, Inspiring Minds</p>
        </div>

        <nav>
            <ul>
                <li><a href="index.php" style="color:#aaa">Home</a></li>
                <li><a href="jobs.php">Jobs</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About</a></li>
            </ul>
        </nav>

</header>