<header>
        <img src="images/Hogwarts-Crest.png" alt="Hogwarts Crest" class="logo">
        <div>
            <h1>Hogwarts School of Witchcraft and Wizardry</h1>
            <p class="slogan">Unlocking Magic, Inspiring Minds</p>
        </div>

        <nav>
            <ul>
                <li><a href="index.php" id="nav_home">Home</a></li>
                <li><a href="about.php" id="nav_about">About</a></li>
                <li><a href="jobs.php" id="nav_jobs">Jobs</a></li>
                <li><a href="apply.php" id="nav_apply">Apply</a></li>
                <li><a href="login.php" id="login_nav">Login</a></li>
            </ul>
        </nav>


        <link rel="stylesheet" href="styles/style.css">
        <style>  
        .slogan {
            font-family: 'Italianno', cursive;
            font-size: 1.8rem;
            color: #ffd66e;
            text-align: center;
            margin-top: 5px;
            text-shadow: 0 0 5px #000000;
        }
        </style>
</header>